//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string Code { get; set; }
        public float Price { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public float Discount { get; set; }
        public int UserId { get; set; }
        public string ImageName { get; set; }
        public string ImageContentType { get; set; }
        public byte[] ImageData { get; set; }

    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
